### ISSUE TITLE
本地构建测试文档

### ISSUE THREAD

**Issue by brucehex** [k8smeetup/kubernetes.github.io#169]
Step1 . Clone code

```
git clone https://github.com/k8smeetup/k8smeetup.github.io
```

Step2. Write the docker-compose.yml file

```
version: '2'
services:
  jekyll:
    image: cargo.caicloud.io/kubernetes/jekyll:v1
    command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - ./k8smeetup.github.io:/srv/jekyll
```

Step3. Run and view the browser

```
docker-compose up -d
````

Open chrome address: http: // localhost:4000
Note: If the localhost is running localhost instead of the server IP
